#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v24
# autospec commit: a88ffdc
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kio-extras
Version  : 25.04.0
Release  : 109
URL      : https://download.kde.org/stable/release-service/25.04.0/src/kio-extras-25.04.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/25.04.0/src/kio-extras-25.04.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/25.04.0/src/kio-extras-25.04.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: kio-extras-data = %{version}-%{release}
Requires: kio-extras-lib = %{version}-%{release}
Requires: kio-extras-license = %{version}-%{release}
Requires: kio-extras-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : gperf
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdnssd-dev
BuildRequires : kdsoap-dev
BuildRequires : kdsoap-ws-discovery-client-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libkexiv2-dev
BuildRequires : libssh-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(OpenEXR)
BuildRequires : pkgconfig(libmtp)
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(libtirpc)
BuildRequires : plasma-activities-dev
BuildRequires : plasma-activities-stats-dev
BuildRequires : qcoro6-dev
BuildRequires : qt6base-dev
BuildRequires : shared-mime-info
BuildRequires : syntax-highlighting-dev
BuildRequires : taglib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
KFileAudioPreview is a plugin for the KFileMetaPreview class in KIO to
allow audio files to be previewed in places like the file open dialog.

%package data
Summary: data components for the kio-extras package.
Group: Data

%description data
data components for the kio-extras package.


%package dev
Summary: dev components for the kio-extras package.
Group: Development
Requires: kio-extras-lib = %{version}-%{release}
Requires: kio-extras-data = %{version}-%{release}
Provides: kio-extras-devel = %{version}-%{release}
Requires: kio-extras = %{version}-%{release}

%description dev
dev components for the kio-extras package.


%package doc
Summary: doc components for the kio-extras package.
Group: Documentation

%description doc
doc components for the kio-extras package.


%package lib
Summary: lib components for the kio-extras package.
Group: Libraries
Requires: kio-extras-data = %{version}-%{release}
Requires: kio-extras-license = %{version}-%{release}

%description lib
lib components for the kio-extras package.


%package license
Summary: license components for the kio-extras package.
Group: Default

%description license
license components for the kio-extras package.


%package locales
Summary: locales components for the kio-extras package.
Group: Default

%description locales
locales components for the kio-extras package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kio-extras-25.04.0
cd %{_builddir}/kio-extras-25.04.0
pushd ..
cp -a kio-extras-25.04.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744932547
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DLIBSSH_LIBRARIES="-lssh" \
-DQT_MAJOR_VERSION=6 \
-DINTERFACE_QT_MAJOR_VERSION=6 \
-DBUILD_TESTING=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DLIBSSH_LIBRARIES="-lssh" \
-DQT_MAJOR_VERSION=6 \
-DINTERFACE_QT_MAJOR_VERSION=6 \
-DBUILD_TESTING=OFF  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1744932547
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kio-extras
cp %{_builddir}/kio-extras-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kio-extras/52039e5c19c950d4c7d6ec5da42ebba2c6def7ee || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/kio-extras/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kio-extras/8287b608d3fa40ef401339fd907ca1260c964123 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kio-extras/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kio-extras/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kio-extras/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kio-extras/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kio-extras/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kio-extras/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kio-extras/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/kio-extras/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kio-extras/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kio-extras/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kio-extras/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kio-extras/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kio-extras/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kio-extras-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/kio-extras/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3 || :
cp %{_builddir}/kio-extras-%{version}/man/LICENSE %{buildroot}/usr/share/package-licenses/kio-extras/67218f86a21c5afe177def300337c7ff8ccf40f9 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kfileaudiopreview6
%find_lang kio-extras_kcms
%find_lang kio6_archive
%find_lang kio6_fish
%find_lang kio6_man
%find_lang kio6_nfs
%find_lang kio6_sftp
%find_lang kio6_smb
%find_lang kio6_thumbnail
%find_lang kio6_activities
%find_lang kio6_afc
%find_lang kio6_filenamesearch
%find_lang kio6_info
%find_lang kio6_mtp
%find_lang kio6_recentlyused
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/wpad-detector-helper
/usr/lib64/libexec/wpad-detector-helper

%files data
%defattr(-,root,root,-)
/usr/share/applications/kcm_netpref.desktop
/usr/share/applications/kcm_proxy.desktop
/usr/share/applications/kcm_trash.desktop
/usr/share/applications/kcm_webshortcuts.desktop
/usr/share/config.kcfg/jpegcreatorsettings5.kcfg
/usr/share/dbus-1/services/org.kde.kmtpd5.service
/usr/share/kio_filenamesearch/kio-filenamesearch-grep
/usr/share/kio_info/kde-info2html
/usr/share/kio_info/kde-info2html.conf
/usr/share/konqueror/dirtree/remote/mtp-network.desktop
/usr/share/qlogging-categories6/kio-extras.categories
/usr/share/qlogging-categories6/kio-extras.renamecategories
/usr/share/remoteview/mtp-network.desktop
/usr/share/solid/actions/solid_mtp.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/KioArchive6/kio_archivebase.h
/usr/include/KioArchive6/kioarchive_version.h
/usr/include/KioArchive6/libkioarchive_export.h
/usr/lib64/cmake/KioArchive6/KioArchive6Config.cmake
/usr/lib64/cmake/KioArchive6/KioArchive6ConfigVersion.cmake
/usr/lib64/cmake/KioArchive6/KioArchiveTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KioArchive6/KioArchiveTargets.cmake

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/ca/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/ca/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/ca/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/ca/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/ca/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/fish/index.docbook
/usr/share/doc/HTML/ca/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/ca/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/info/index.docbook
/usr/share/doc/HTML/ca/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/man/index.docbook
/usr/share/doc/HTML/ca/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/ca/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/ca/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/smb/index.docbook
/usr/share/doc/HTML/ca/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/tar/index.docbook
/usr/share/doc/HTML/ca/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/ca/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/xz/index.docbook
/usr/share/doc/HTML/ca/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/ca/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/ca@valencia/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/ca@valencia/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/ca@valencia/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/ca@valencia/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/ca@valencia/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/de/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/de/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/de/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/de/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/de/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/de/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/fish/index.docbook
/usr/share/doc/HTML/de/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/de/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/info/index.docbook
/usr/share/doc/HTML/de/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/man/index.docbook
/usr/share/doc/HTML/de/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/de/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/de/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/smb/index.docbook
/usr/share/doc/HTML/de/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/tar/index.docbook
/usr/share/doc/HTML/de/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/de/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/xz/index.docbook
/usr/share/doc/HTML/de/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/de/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/en/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/en/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/en/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/en/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/en/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/en/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/fish/index.docbook
/usr/share/doc/HTML/en/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/en/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/info/index.docbook
/usr/share/doc/HTML/en/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/man/index.docbook
/usr/share/doc/HTML/en/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/en/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/en/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/smb/index.docbook
/usr/share/doc/HTML/en/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/tar/index.docbook
/usr/share/doc/HTML/en/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/en/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/xz/index.docbook
/usr/share/doc/HTML/en/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/en/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/es/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/es/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/es/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/es/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/es/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/es/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/fish/index.docbook
/usr/share/doc/HTML/es/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/es/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/info/index.docbook
/usr/share/doc/HTML/es/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/man/index.docbook
/usr/share/doc/HTML/es/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/es/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/es/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/smb/index.docbook
/usr/share/doc/HTML/es/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/tar/index.docbook
/usr/share/doc/HTML/es/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/es/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/xz/index.docbook
/usr/share/doc/HTML/es/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/es/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/et/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/et/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/fish/index.docbook
/usr/share/doc/HTML/et/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/et/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/info/index.docbook
/usr/share/doc/HTML/et/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/man/index.docbook
/usr/share/doc/HTML/et/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/et/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/et/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/smb/index.docbook
/usr/share/doc/HTML/et/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/tar/index.docbook
/usr/share/doc/HTML/et/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/et/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/et/kioworker6/xz/index.docbook
/usr/share/doc/HTML/fr/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/fr/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/fr/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/fr/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/fr/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/fr/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/fish/index.docbook
/usr/share/doc/HTML/fr/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/fr/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/info/index.docbook
/usr/share/doc/HTML/fr/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/man/index.docbook
/usr/share/doc/HTML/fr/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/fr/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/fr/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/smb/index.docbook
/usr/share/doc/HTML/fr/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/tar/index.docbook
/usr/share/doc/HTML/fr/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/fr/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/fr/kioworker6/xz/index.docbook
/usr/share/doc/HTML/gl/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/gl/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/fish/index.docbook
/usr/share/doc/HTML/gl/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/gl/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/info/index.docbook
/usr/share/doc/HTML/gl/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/man/index.docbook
/usr/share/doc/HTML/gl/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/gl/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/gl/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/tar/index.docbook
/usr/share/doc/HTML/gl/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/gl/kioworker6/xz/index.docbook
/usr/share/doc/HTML/it/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/it/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/it/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/it/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/it/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/it/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/fish/index.docbook
/usr/share/doc/HTML/it/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/it/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/info/index.docbook
/usr/share/doc/HTML/it/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/man/index.docbook
/usr/share/doc/HTML/it/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/it/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/it/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/smb/index.docbook
/usr/share/doc/HTML/it/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/tar/index.docbook
/usr/share/doc/HTML/it/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/it/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/xz/index.docbook
/usr/share/doc/HTML/it/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/it/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/nb/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/nb/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/nb/kioworker6/man/index.docbook
/usr/share/doc/HTML/nb/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/nb/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/nl/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/nl/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/nl/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/nl/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/nl/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/nl/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/fish/index.docbook
/usr/share/doc/HTML/nl/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/nl/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/info/index.docbook
/usr/share/doc/HTML/nl/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/man/index.docbook
/usr/share/doc/HTML/nl/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/nl/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/nl/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/smb/index.docbook
/usr/share/doc/HTML/nl/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/tar/index.docbook
/usr/share/doc/HTML/nl/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/nl/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/xz/index.docbook
/usr/share/doc/HTML/nl/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/nl/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/pt/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/pt/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/pt/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/pt/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/pt/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/pt/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/fish/index.docbook
/usr/share/doc/HTML/pt/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/pt/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/info/index.docbook
/usr/share/doc/HTML/pt/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/man/index.docbook
/usr/share/doc/HTML/pt/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/pt/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/pt/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/smb/index.docbook
/usr/share/doc/HTML/pt/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/tar/index.docbook
/usr/share/doc/HTML/pt/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/pt/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/pt/kioworker6/xz/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/fish/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/info/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/man/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/smb/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/tar/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/pt_BR/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kioworker6/xz/index.docbook
/usr/share/doc/HTML/ru/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/ru/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/ru/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/ru/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/ru/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/ru/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/fish/index.docbook
/usr/share/doc/HTML/ru/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/ru/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/info/index.docbook
/usr/share/doc/HTML/ru/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/man/index.docbook
/usr/share/doc/HTML/ru/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/ru/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/ru/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/smb/index.docbook
/usr/share/doc/HTML/ru/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/tar/index.docbook
/usr/share/doc/HTML/ru/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/ru/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/xz/index.docbook
/usr/share/doc/HTML/ru/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/ru/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/sl/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/sl/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/sl/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/sl/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/sl/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/sl/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/fish/index.docbook
/usr/share/doc/HTML/sl/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/sl/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/info/index.docbook
/usr/share/doc/HTML/sl/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/man/index.docbook
/usr/share/doc/HTML/sl/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/sl/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/smb/index.docbook
/usr/share/doc/HTML/sl/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/tar/index.docbook
/usr/share/doc/HTML/sl/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/sl/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/xz/index.docbook
/usr/share/doc/HTML/sl/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/sl/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/sr/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/sr/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/sr/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/sr/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/sr/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/fish/index.docbook
/usr/share/doc/HTML/sr/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/sr/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/info/index.docbook
/usr/share/doc/HTML/sr/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/man/index.docbook
/usr/share/doc/HTML/sr/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/sr/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/sr/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/smb/index.docbook
/usr/share/doc/HTML/sr/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/tar/index.docbook
/usr/share/doc/HTML/sr/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/sr/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/sr/kioworker6/xz/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/fish/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/info/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/man/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/smb/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/tar/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/sr@latin/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kioworker6/xz/index.docbook
/usr/share/doc/HTML/sv/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/sv/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/sv/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/sv/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/sv/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/sv/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/fish/index.docbook
/usr/share/doc/HTML/sv/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/sv/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/info/index.docbook
/usr/share/doc/HTML/sv/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/man/index.docbook
/usr/share/doc/HTML/sv/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/sv/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/sv/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/smb/index.docbook
/usr/share/doc/HTML/sv/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/tar/index.docbook
/usr/share/doc/HTML/sv/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/sv/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/xz/index.docbook
/usr/share/doc/HTML/sv/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/sv/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/tr/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/tr/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/tr/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/tr/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/tr/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/tr/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/fish/index.docbook
/usr/share/doc/HTML/tr/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/tr/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/info/index.docbook
/usr/share/doc/HTML/tr/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/man/index.docbook
/usr/share/doc/HTML/tr/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/tr/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/tr/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/smb/index.docbook
/usr/share/doc/HTML/tr/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/tar/index.docbook
/usr/share/doc/HTML/tr/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/tr/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/xz/index.docbook
/usr/share/doc/HTML/tr/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/tr/kioworker6/zstd/index.docbook
/usr/share/doc/HTML/uk/kcontrol6/netpref/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol6/netpref/index.docbook
/usr/share/doc/HTML/uk/kcontrol6/proxy/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol6/proxy/index.docbook
/usr/share/doc/HTML/uk/kcontrol6/trash/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol6/trash/index.docbook
/usr/share/doc/HTML/uk/kcontrol6/webshortcuts/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol6/webshortcuts/index.docbook
/usr/share/doc/HTML/uk/kioworker6/bzip2/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/bzip2/index.docbook
/usr/share/doc/HTML/uk/kioworker6/fish/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/fish/index.docbook
/usr/share/doc/HTML/uk/kioworker6/gzip/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/gzip/index.docbook
/usr/share/doc/HTML/uk/kioworker6/info/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/info/index.docbook
/usr/share/doc/HTML/uk/kioworker6/man/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/man/index.docbook
/usr/share/doc/HTML/uk/kioworker6/nfs/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/nfs/index.docbook
/usr/share/doc/HTML/uk/kioworker6/sftp/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/sftp/index.docbook
/usr/share/doc/HTML/uk/kioworker6/smb/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/smb/index.docbook
/usr/share/doc/HTML/uk/kioworker6/tar/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/tar/index.docbook
/usr/share/doc/HTML/uk/kioworker6/thumbnail/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/thumbnail/index.docbook
/usr/share/doc/HTML/uk/kioworker6/xz/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/xz/index.docbook
/usr/share/doc/HTML/uk/kioworker6/zstd/index.cache.bz2
/usr/share/doc/HTML/uk/kioworker6/zstd/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkioarchive6.so.6.0.0
/V3/usr/lib64/qt6/plugins/kcm_trash.so
/V3/usr/lib64/qt6/plugins/kf6/kded/filenamesearchmodule.so
/V3/usr/lib64/qt6/plugins/kf6/kded/wpad-detector.so
/V3/usr/lib64/qt6/plugins/kf6/kfileitemaction/forgetfileitemaction.so
/V3/usr/lib64/qt6/plugins/kf6/kfileitemaction/kactivitymanagerd_fileitem_linking_plugin.so
/V3/usr/lib64/qt6/plugins/kf6/kio/activities.so
/V3/usr/lib64/qt6/plugins/kf6/kio/archive.so
/V3/usr/lib64/qt6/plugins/kf6/kio/filter.so
/V3/usr/lib64/qt6/plugins/kf6/kio/fish.so
/V3/usr/lib64/qt6/plugins/kf6/kio/info.so
/V3/usr/lib64/qt6/plugins/kf6/kio/kio_filenamesearch.so
/V3/usr/lib64/qt6/plugins/kf6/kio/man.so
/V3/usr/lib64/qt6/plugins/kf6/kio/mtp.so
/V3/usr/lib64/qt6/plugins/kf6/kio/nfs.so
/V3/usr/lib64/qt6/plugins/kf6/kio/recentlyused.so
/V3/usr/lib64/qt6/plugins/kf6/kio/sftp.so
/V3/usr/lib64/qt6/plugins/kf6/kio/thumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/kiod/kmtpd.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/audiothumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/comicbookthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/cursorthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/directorythumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/djvuthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/ebookthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/exrthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/imagethumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/jpegthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/kraorathumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/opendocumentthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/svgthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/textthumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/windowsexethumbnail.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/windowsimagethumbnail.so
/V3/usr/lib64/qt6/plugins/kfileaudiopreview.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_netpref.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_proxy.so
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_webshortcuts.so
/usr/lib64/libkioarchive6.so.6
/usr/lib64/libkioarchive6.so.6.0.0
/usr/lib64/qt6/plugins/kcm_trash.so
/usr/lib64/qt6/plugins/kf6/kded/filenamesearchmodule.so
/usr/lib64/qt6/plugins/kf6/kded/wpad-detector.so
/usr/lib64/qt6/plugins/kf6/kfileitemaction/forgetfileitemaction.so
/usr/lib64/qt6/plugins/kf6/kfileitemaction/kactivitymanagerd_fileitem_linking_plugin.so
/usr/lib64/qt6/plugins/kf6/kio/activities.so
/usr/lib64/qt6/plugins/kf6/kio/archive.so
/usr/lib64/qt6/plugins/kf6/kio/filter.so
/usr/lib64/qt6/plugins/kf6/kio/fish.so
/usr/lib64/qt6/plugins/kf6/kio/info.so
/usr/lib64/qt6/plugins/kf6/kio/kio_filenamesearch.so
/usr/lib64/qt6/plugins/kf6/kio/man.so
/usr/lib64/qt6/plugins/kf6/kio/mtp.so
/usr/lib64/qt6/plugins/kf6/kio/nfs.so
/usr/lib64/qt6/plugins/kf6/kio/recentlyused.so
/usr/lib64/qt6/plugins/kf6/kio/sftp.so
/usr/lib64/qt6/plugins/kf6/kio/thumbnail.so
/usr/lib64/qt6/plugins/kf6/kiod/kmtpd.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/audiothumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/comicbookthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/cursorthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/directorythumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/djvuthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/ebookthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/exrthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/imagethumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/jpegthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/kraorathumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/opendocumentthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/svgthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/textthumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/windowsexethumbnail.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/windowsimagethumbnail.so
/usr/lib64/qt6/plugins/kfileaudiopreview.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_netpref.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_proxy.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_webshortcuts.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kio-extras/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/kio-extras/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kio-extras/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/kio-extras/52039e5c19c950d4c7d6ec5da42ebba2c6def7ee
/usr/share/package-licenses/kio-extras/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kio-extras/67218f86a21c5afe177def300337c7ff8ccf40f9
/usr/share/package-licenses/kio-extras/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kio-extras/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/kio-extras/8287b608d3fa40ef401339fd907ca1260c964123
/usr/share/package-licenses/kio-extras/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/kio-extras/a0193e3fccf86c17dc71e3f6c0ac0b535e06bea3
/usr/share/package-licenses/kio-extras/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/kio-extras/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/kio-extras/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f kfileaudiopreview6.lang -f kio-extras_kcms.lang -f kio6_archive.lang -f kio6_fish.lang -f kio6_man.lang -f kio6_nfs.lang -f kio6_sftp.lang -f kio6_smb.lang -f kio6_thumbnail.lang -f kio6_activities.lang -f kio6_afc.lang -f kio6_filenamesearch.lang -f kio6_info.lang -f kio6_mtp.lang -f kio6_recentlyused.lang
%defattr(-,root,root,-)

